-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, U.GENDER GENDER, COUNT(DISTINCT O.USER_ID) USERS
FROM ONLINE_SALE O LEFT JOIN  USER_INFO U  ON  U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER;