-- 코드를 입력하세요
SELECT FLAVOR
FROM 
    (SELECT F.FLAVOR FLAVOR, SUM(F.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) ORDERS
     FROM FIRST_HALF F, JULY J
     WHERE F.FLAVOR=J.FLAVOR
     GROUP BY F.FLAVOR
     ORDER BY ORDERS DESC
    ) AS ICECREAM
LIMIT 3;